# Site settings
title:          Sunny oaks
description:    ""
baseurl:        "/blog1"
#url:            "https://sunnyoaks.github.io/blog/"

# Author
author:
  name:         Anna Miczka
  email:       anna.miczka@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
